name: Kernel
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 480
    steps: 
    - uses: fastai/workflows/ssh@master
      with:
        ssh_key: ${{ secrets.SSH_KEY }}
        key_file: id_ecdsa
    - uses: actions/checkout@v2
    - name: Clone Kernel..
      run: |
        gpg --import nfsgpg.key
        git config --global commit.gpgsign true
        git config --global user.signingkey $GPG_KEY
        git config --global gpg.program gpg2
        export GPG_TTY=$(tty)
        echo "test" | gpg2 --clearsign
        bash kernel.sh
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GPG_KEY: ${{ secrets.GPG_KEY }}
    - name: Session Setup
      uses: mxschmitt/action-tmate@master
